### ISSUE TITLE
Investigate Go Vendoring

### ISSUE THREAD

**Issue by vladimirvivien** [vladimirvivien/automi#17]
Look into vendoring for project.

**Comment by ottogiron** [comment]
I've been using govendor for a while https://github.com/kardianos/govendor and it has worked well. Here's  a working example  https://github.com/ottogiron/automi/tree/testbranch.

I really like the automi idea, at some point I'll need something like this. 

BTW I can provide a PR for vendoring if you are interested :).

**Comment by vladimirvivien** [comment]
@ottogiron thanks the interest.  I am interested in Vendoring as long as it's compatible with the language-supported build-flow.  Meaning, that it works with GOPATH, support all existing go tool chain, etc.  I am on a pause right now, you are welcome to drop in the vendor PR.  Thanks for the help.

**Comment by vladimirvivien** [comment]
Decided to keep core automi independent and only relying on built-in packages.  Eventually, non-core sources, sinks will be implemented as separate repos.
