### ISSUE TITLE
Reactivex

### ISSUE THREAD

**Issue by isaldana** [vladimirvivien/automi#20]
Is the plan to implement some/most of the functions from Reactivex?  Will you add support to emit multiple items such as Storm does with tuples?  How will you handle errors?

**Comment by vladimirvivien** [comment]
@isaldana thanks for looking the project.  The project's focus in on stream processing (which may overlap with the reactive movement). At this point, you can emit whatever type you want from a stream.  There is no specific type required (though there is a tuple.KV type predefined for key/value types for convenience).  As far as emitting multiple items (assuming you mean to multiple streams at once), there is plan for more operators and one could be an Emitter that broadcast items to multiple streams.

Current version simply logs errors.  Error handling can be done in a number of ways and I am looking for input / suggestions for a more structured approach.
