### ISSUE TITLE
nifty overlap!

### ISSUE THREAD

**Issue by sdboyer** [vladimirvivien/automi#22]
hi! just wanted to drop a line to note that i'd written something similar to this a while back - https://github.com/sdboyer/transducers-go 

i ended up abandoning it, and i suspect that you probably have all the patterns explored in there present in here. but, given the similarities, i figured i'd just drop a link 😸

**Comment by sdboyer** [comment]
nothing actually to do here, so closing :)

**Comment by vladimirvivien** [comment]
@sdboyer Thanks for letting me know!  It's an idea that seems to fit naturally with channels.  My inspiration came from those tons of Java-based stream processors out there.  I wish I had more time to devote to it.  But will try to make something useful out of it!

**Comment by sdboyer** [comment]
@vladimirvivien sure! with any luck, you'll find something useful there, even if it's just a glimmering of an idea ✨✨ 

i suspect the most possibly-interesting for your purposes would be the high-level patterns that combine the individual parts together. those are here: https://github.com/sdboyer/transducers-go/blob/master/processors.go

**Comment by vladimirvivien** [comment]
@sdboyer Ok thanks for pointing processors.go out for me.  Hope to eventually get back to this code and will check it out.  Thanks again!
