### ISSUE TITLE
CSV example

### ISSUE THREAD

**Issue by joeblew99** [vladimirvivien/automi#5]
This looks really useful. I have a project at the moment where I need to pull a few CSV files over http, filter out some crap rows, map the data into my structs, and lump them into the dB.

Basically ETL stuff that your example in the read me dies.

Is the example and the data that drives it anywhere ?

Thanks again for this ....

**Comment by vladimirvivien** [comment]
@joeblew99 first apologies for the late reply. The API has changed considerably since the start of the year. Look for new updated examples that take advantage of the new API design to arrive soon on the website.  Thanks for checking it out.

**Comment by joeblew99** [comment]
Thanks.

It looks like pixie dust and unicorns at the moment.
Are there any examples
I have been playing with glow, which I am sure you know about. It takes a
very different approach in that it allows the CFG ( computation flow graph)
to be reconfigured easily.

I have a project right now where I need to stream about 4 pt per month
through a system and so am investing a fair bit of time building up the
archi.

Joe

**Comment by vladimirvivien** [comment]
@joeblew99 sorry i missed this.  Since my last reply, I have added an example folder to the project.  No pixxie dust :)  File an issue if you run into problems.  Thanks!
